### ISSUE TITLE
notify not appears in extensions board

### ISSUE THREAD

**Issue by rizys** [moay/flarum-notify#2]
Hi :)

I try to install your ext but i can't solve my problem...
Composer allows me to install many ext without any trouble but yours doesn't appears in ext board !

Thanks,
Rémi

**Comment by moay** [comment]
Hi @rizys,

sorry for that. I didn't have the time to make the extension work via composer yet. I'll do that when flarum reaches a more stable state...

So for now, you can just try to upload it the old fashioned way. ;)

**Comment by gdude2002** [comment]
@moay Installing it manually (Extracting the zip file to the `extensions/` dir) doesn't appear to be enough to get it to show up in the grid of extensions in the settings - is there something else that needs to be done?
